package com.myspace.hdi_cabina_ajuste;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Poliza")
@javax.persistence.Entity
public class Poliza implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Numero")
	private long numero;
	@org.kie.api.definition.type.Label("Vigencia")
	private java.util.Date vigencia;
	@org.kie.api.definition.type.Label("Estatus")
	private java.lang.String estatus;
	@org.kie.api.definition.type.Label("Coberturas")
	private java.util.List<java.lang.String> coberturas;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "POLIZA_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "POLIZA_ID_SEQ", name = "POLIZA_ID_GENERATOR")
	private java.lang.Long id;

	public Poliza() {
	}

	public long getNumero() {
		return this.numero;
	}

	public void setNumero(long numero) {
		this.numero = numero;
	}

	public java.util.Date getVigencia() {
		return this.vigencia;
	}

	public void setVigencia(java.util.Date vigencia) {
		this.vigencia = vigencia;
	}

	public java.lang.String getEstatus() {
		return this.estatus;
	}

	public void setEstatus(java.lang.String estatus) {
		this.estatus = estatus;
	}

	public java.util.List<java.lang.String> getCoberturas() {
		return this.coberturas;
	}

	public void setCoberturas(java.util.List<java.lang.String> coberturas) {
		this.coberturas = coberturas;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public Poliza(long numero, java.util.Date vigencia,
			java.lang.String estatus,
			java.util.List<java.lang.String> coberturas, java.lang.Long id) {
		this.numero = numero;
		this.vigencia = vigencia;
		this.estatus = estatus;
		this.coberturas = coberturas;
		this.id = id;
	}

}