package com.myspace.hdi_cabina_ajuste;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Reporte")
@javax.persistence.Entity
public class Reporte implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Numero")
	private long numero;
	@org.kie.api.definition.type.Label("Fecha y Hora")
	private java.util.Date fecha;
	@org.kie.api.definition.type.Label("Placas del automovil")
	private java.lang.String placas;
	@org.kie.api.definition.type.Label("Color del automovil")
	private java.lang.String color;
	@org.kie.api.definition.type.Label("Nombre del conductor")
	private java.lang.String conductor;
	@org.kie.api.definition.type.Label("Telefono de contacto")
	private java.lang.String telefono;
	@org.kie.api.definition.type.Label("Ubicacion del siniestro")
	private java.lang.String ubicacion;
	@org.kie.api.definition.type.Label("Descripcion del siniestro")
	private java.lang.String descripcion;
	@org.kie.api.definition.type.Label("Folio del siniestro")
	private java.lang.String siniestro;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "REPORTE_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "REPORTE_ID_SEQ", name = "REPORTE_ID_GENERATOR")
	private java.lang.Long id;

	public Reporte() {
	}

	public long getNumero() {
		return this.numero;
	}

	public void setNumero(long numero) {
		this.numero = numero;
	}

	public java.util.Date getFecha() {
		return this.fecha;
	}

	public void setFecha(java.util.Date fecha) {
		this.fecha = fecha;
	}

	public java.lang.String getPlacas() {
		return this.placas;
	}

	public void setPlacas(java.lang.String placas) {
		this.placas = placas;
	}

	public java.lang.String getColor() {
		return this.color;
	}

	public void setColor(java.lang.String color) {
		this.color = color;
	}

	public java.lang.String getConductor() {
		return this.conductor;
	}

	public void setConductor(java.lang.String conductor) {
		this.conductor = conductor;
	}

	public java.lang.String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(java.lang.String telefono) {
		this.telefono = telefono;
	}

	public java.lang.String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(java.lang.String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public java.lang.String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(java.lang.String descripcion) {
		this.descripcion = descripcion;
	}

	public java.lang.String getSiniestro() {
		return this.siniestro;
	}

	public void setSiniestro(java.lang.String siniestro) {
		this.siniestro = siniestro;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public Reporte(long numero, java.util.Date fecha, java.lang.String placas,
			java.lang.String color, java.lang.String conductor,
			java.lang.String telefono, java.lang.String ubicacion,
			java.lang.String descripcion, java.lang.String siniestro,
			java.lang.Long id) {
		this.numero = numero;
		this.fecha = fecha;
		this.placas = placas;
		this.color = color;
		this.conductor = conductor;
		this.telefono = telefono;
		this.ubicacion = ubicacion;
		this.descripcion = descripcion;
		this.siniestro = siniestro;
		this.id = id;
	}

}